// Code generated by "stringer -type=WeaponType"; DO NOT EDIT.

package component

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sword-0]
	_ = x[Spear-1]
	_ = x[Flail-2]
	_ = x[Mace-3]
	_ = x[Bow-4]
	_ = x[Staff-5]
	_ = x[Fist-6]
}

const _WeaponType_name = "SwordSpearFlailMaceBowStaffFist"

var _WeaponType_index = [...]uint8{0, 5, 10, 15, 19, 22, 27, 31}

func (i WeaponType) String() string {
	if i >= WeaponType(len(_WeaponType_index)-1) {
		return "WeaponType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeaponType_name[_WeaponType_index[i]:_WeaponType_index[i+1]]
}
