Package = "shapes"
AssetPath = "../../../sprites"
OutFile = "character-shapes.go"
Files = [
    "player/Chica-SpearDown.aseprite",
    "player/Chica-WalkDown.aseprite",
    "player/Chica-Idle-Down.aseprite",

    "enemies/Gel.aseprite"
]