// Code generated by "stringer -type=Direction"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Up-0]
	_ = x[Right-1]
	_ = x[UpRight-2]
	_ = x[RightDown-3]
	_ = x[Down-4]
	_ = x[DownLeft-5]
	_ = x[Left-6]
	_ = x[UpLeft-7]
}

const _Direction_name = "UpRightUpRightRightDownDownDownLeftLeftUpLeft"

var _Direction_index = [...]uint8{0, 2, 7, 14, 23, 27, 35, 39, 45}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
